GET http://localhost:8080/ping

###
GET http://localhost:8080/users/1

###
POST http://localhost:8080/users 

{
    "id": "12",
    "first_name": "Rajesh",
    "last_name": "Reddy",
    "email":"rajesh.reddy@test.com"
}

###
GET http://localhost:8080/dummy